[[SOFA]]
arch = "aarch64"
git-tree-sha1 = "c8abfc43fef84ecff8cced411f3a961455a6c002"
os = "macos"

    [[SOFA.download]]
    sha256 = "8031b177b4bfb68129c9c12222d915288ee22bb700dc5a168aecc074f9adce6e"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.aarch64-apple-darwin.tar.gz"
[[SOFA]]
arch = "aarch64"
git-tree-sha1 = "1ae9da17396d72b81d5f7bb6b4ff583f529e96c8"
libc = "glibc"
os = "linux"

    [[SOFA.download]]
    sha256 = "faaacfd30df67b3a1cd5e035f5a4da572162c3832af2384dcd32dc69fed95a99"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.aarch64-linux-gnu.tar.gz"
[[SOFA]]
arch = "aarch64"
git-tree-sha1 = "1e319fb075c1372af0f2c95a1df2353c066b626a"
libc = "musl"
os = "linux"

    [[SOFA.download]]
    sha256 = "eb3bcd9bbcdf55b01d804b1301b95f0cdef7c1a6dcb7ce9101b8f2ea3ff6e123"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.aarch64-linux-musl.tar.gz"
[[SOFA]]
arch = "aarch64"
git-tree-sha1 = "89761e893893a36e5c227793c39a563fc09e901f"
os = "freebsd"

    [[SOFA.download]]
    sha256 = "8d3b406a019f020b8901033f10016b214584e27f0ba68b0897602329e51d78da"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.aarch64-unknown-freebsd.tar.gz"
[[SOFA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89cef57a4d065acbbf000fdb18990debe824188c"
libc = "glibc"
os = "linux"

    [[SOFA.download]]
    sha256 = "1025d6ded1f74fe29653c0040bb125c9942ed452060d8e92f868ba1574df1ccf"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.armv6l-linux-gnueabihf.tar.gz"
[[SOFA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "41352e5b1d7a86659f2e015cb91859205d802d3e"
libc = "musl"
os = "linux"

    [[SOFA.download]]
    sha256 = "8abe284eea313d379eb639fb920e6cdb532db0836ea28b3bf8d83211d443d0c2"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.armv6l-linux-musleabihf.tar.gz"
[[SOFA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5ef837437771bd3f658476a6f6648b0e8a978856"
libc = "glibc"
os = "linux"

    [[SOFA.download]]
    sha256 = "4adc5bf6a64650ac5edc3bf92ce605abe2b03c2271435fe8fcc2b0f6e9dd9318"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.armv7l-linux-gnueabihf.tar.gz"
[[SOFA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5394bf2d8a54722df5cd7fecc1af2b34130f674c"
libc = "musl"
os = "linux"

    [[SOFA.download]]
    sha256 = "84bb1b65f102ff1df185a49e9a49e8c9a4e2e467b6d82ec12752fe39e93d6ea6"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.armv7l-linux-musleabihf.tar.gz"
[[SOFA]]
arch = "i686"
git-tree-sha1 = "a2b12488138bb4cc9ec70d3f0aef8760c0d39cd7"
libc = "glibc"
os = "linux"

    [[SOFA.download]]
    sha256 = "b57a48fe7ab279e9074991afec0b63cec02bf46b08639b485a94509eceb5e32e"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.i686-linux-gnu.tar.gz"
[[SOFA]]
arch = "i686"
git-tree-sha1 = "55d5676afb52b62e97e88da6d96f2223ae93d267"
libc = "musl"
os = "linux"

    [[SOFA.download]]
    sha256 = "540d384539ef2ebfe9b1a15d9660c726e369c7b635ff998f1e6eb873469502d2"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.i686-linux-musl.tar.gz"
[[SOFA]]
arch = "i686"
git-tree-sha1 = "4153597ad8b7cc81cda816b6399464f8d88e6450"
os = "windows"

    [[SOFA.download]]
    sha256 = "9c822b34808af46de823ab72980867098f6d5b27bf7daf6ca9246afab3dc7e77"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.i686-w64-mingw32.tar.gz"
[[SOFA]]
arch = "powerpc64le"
git-tree-sha1 = "a94d3c7c29a4b9b95c29bc2931ae34f6e42a4e45"
libc = "glibc"
os = "linux"

    [[SOFA.download]]
    sha256 = "ed2f9d2227b3f1081cc512d07cb493d7c2df0cdf600ebb19268fc34de850aabe"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.powerpc64le-linux-gnu.tar.gz"
[[SOFA]]
arch = "riscv64"
git-tree-sha1 = "7b029d22ac2a654f61d2adc9054735bbff52b070"
libc = "glibc"
os = "linux"

    [[SOFA.download]]
    sha256 = "6fa2efaa6cbc2cf7da8bf3153f35ef8b81c546fa2be0a8f7bf3e106f314d66b5"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.riscv64-linux-gnu.tar.gz"
[[SOFA]]
arch = "x86_64"
git-tree-sha1 = "21b0de5044958521c3c2dc9f4e3c9475c6300169"
os = "macos"

    [[SOFA.download]]
    sha256 = "2854fc1f9735ea5bb2b1f8fee91d37d039394e6593e76891d91ad420f476526d"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.x86_64-apple-darwin.tar.gz"
[[SOFA]]
arch = "x86_64"
git-tree-sha1 = "7db1171bad765707f9571a80f8d5e29c084987a5"
libc = "glibc"
os = "linux"

    [[SOFA.download]]
    sha256 = "ba1c1bb72f63b4296c2bb29cb62842e0b52b1bc63953bbce0e8ffa35a1c0304b"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.x86_64-linux-gnu.tar.gz"
[[SOFA]]
arch = "x86_64"
git-tree-sha1 = "d1daba7097327d4768214e0e8e6a948434cc93d5"
libc = "musl"
os = "linux"

    [[SOFA.download]]
    sha256 = "b70aefc081f407c997136a8131cc09481541323598d282c5ffd2440d011e5c45"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.x86_64-linux-musl.tar.gz"
[[SOFA]]
arch = "x86_64"
git-tree-sha1 = "19f8389aa98893308abfedb739aa862bbb8dd47c"
os = "freebsd"

    [[SOFA.download]]
    sha256 = "fe55c1ee986b9731651d203d3914c137e4ddd9168af40a92ab826e2379c0a815"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.x86_64-unknown-freebsd.tar.gz"
[[SOFA]]
arch = "x86_64"
git-tree-sha1 = "549b98a9d85d76e9d981eb282e00618f20f60b00"
os = "windows"

    [[SOFA.download]]
    sha256 = "dd1f2f830cfc00bf98553f889a9083cc5c016c824042390aa9278ee53c7adc33"
    url = "https://github.com/JuliaBinaryWrappers/SOFA_jll.jl/releases/download/SOFA-v2021.5.12+0/SOFA.v2021.5.12.x86_64-w64-mingw32.tar.gz"
