# Autogenerated wrapper script for SOFA_jll for aarch64-apple-darwin
export libsofa_c

JLLWrappers.@generate_wrapper_header("SOFA")
JLLWrappers.@declare_library_product(libsofa_c, "@rpath/libsofa_c.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libsofa_c,
        "lib/libsofa_c.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
